---
# vars file for post-install
USRNM: thenewuser
COMM: welcome to the era of new variable
ntp0: 0.north-america.pool.ntp.org
ntp1: 1.north-america.pool.ntp.org
ntp2: 2.north-america.pool.ntp.org
ntp3: 3.north-america.pool.ntp.org
mydir: /opt/dir22
